### ISSUE TITLE
Onwer widget is not requesting new profiles when writing a name

### ISSUE THREAD

**Issue by jackbravo** [wizeline/project-lab#334]
Triggered from slack: https://wizeline.slack.com/archives/C012JNFUN1J/p1654198356197589

How to reproduce?

1. edit any project
2. try to change the owner to any owner that doesn't appear on the first requested list
3. if you open the browser network tab console you can notice that no requests are being made to get more profiles past the initial load

**Comment by LuisTejedaS** [comment]
@jackbravo reviewing the code the options available in the select are just the members of the project, so this list is loaded while displaying the project details page. So all members should be on the list. Maybe you are thinking of changing the behavior so all of the profiles are listed? Even if they are not members?
